### ISSUE TITLE
question about using cnl::sqrt()

### ISSUE THREAD

**Issue by RallyTronics** [johnmcfarlane/cnl#221]
I modified your elastic_example2() example as follows:

    // A type such as elastic_integer can be used to specialize fixed_point.
    // Now arithmetic operations are more efficient and less error-prone.
    auto b = elastic_number<32, -28, unsigned>{ 15.9375 };
    auto bb = b * b;
    cout << bb << endl;  // "254.00390625"
    static_assert(is_same<decltype(bb), elastic_number<64, -56, unsigned>>::value, "");

    auto bsqrt = cnl::sqrt(bb);
    cout << bsqrt << endl;

I am unable to get the code to compile in VS2017 after adding the sqrt call, the primary error is 

**1>f:\mtsbx\fixed_point\fixed_point\cnl-develop\include\cnl\num_traits.h(130): error C2504: 'cnl::signed_integer_cannot_have<64>::digits_because_maximum_is<63>': base class undefined**

It appears it is trying to place the result into a signed type rather than an unsigned type.   Is this expected behavior?

**Comment by johnmcfarlane** [comment]
The signed type is introduced by a check for negative input [here](https://github.com/johnmcfarlane/cnl/blob/912eb1901c78b4b5b68330588f0bb9c1634f4896/include/cnl/bits/fixed_point/extras.h#L113). This is tricky to do correctly without using an extra bit due to [problems with comparing signed and unsigned integers](https://godbolt.org/g/xU4aTB). I'm looking at a solution.

However, even if you change the type of `b` to `elastic_number<31, -27, unsigned>`, you'll find another problem with the call to `cnl::sqrt`: that function unfortunately requires a double-width type in order to get decent precision. In this case, that means a 128-bit unsigned integer will be required and as you are using MSVC, I'm afraid that's going to be tricky. You could maybe use [Abseil](https://abseil.io/) which has [a 128-bit type](https://github.com/abseil/abseil-cpp/blob/master/absl/numeric/int128.h) although I've not tested it with CNL so it may have some compatibility issues.

So short answer: change `b` to `elastic_number<15, -11, unsigned>` like so

    auto b = elastic_number<15, -11, unsigned>{15.9375};
    auto bb = b*b;

    cout << bb << endl;  // "254.00390625"
    static_assert(is_same<decltype(bb), elastic_number<30, -22, unsigned>>::value, "");

    auto bsqrt = cnl::sqrt(bb);
    cout << bsqrt << endl;

or downcast the input to `cnl::sqrt`

    auto b = elastic_number<32, -28, unsigned>{15.9375};
    auto bb = b*b;

    cout << bb << endl;  // "254.00390625"
    static_assert(is_same<decltype(bb), elastic_number<64, -56, unsigned>>::value, "");

    auto bsqrt = cnl::sqrt(elastic_number<32, -24, unsigned>{bb});
    cout << bsqrt << endl;

to make it compile.

Longer term, I'll look at fixing the unsigned comparison problem.

Thanks,
John

**Comment by RallyTronics** [comment]
Thank you for the prompt response.  In my real work I am using boost::multiprecision types so getting wider won't be an issue.  I wasn't aware of abseil so thanks for that as well.

**Comment by johnmcfarlane** [comment]
Your welcome! The signed error is fixed in the *develop* branch. LMK if there's anything else I can help with.

**Comment by johnmcfarlane** [comment]
FYI issue with `cnl::sqrt` using double-width integers is addressed in v2 as of #751.
