### ISSUE TITLE
i have another sqrt question

### ISSUE THREAD

**Issue by RallyTronics** [johnmcfarlane/cnl#226]
I am running into issues using sqrt with the boost multiprecision types.  For example:

typedef elastic_number<256, -9, boost::multiprecision::int256_t> length_t;
length_t x = length_t{ 10000 };
x = static_cast<length_t>(cnl::sqrt(x));
cout << x << endl;

1>f:\mtsbx\fixed_point\fixed_point\cnl-develop\include\cnl\bits\fixed_point\extras.h(58): error C2678: binary '<<': no operator found which takes a left-hand operand of type 'boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<**513,513**,boost::multiprecision::signed_magnitude,boost::multiprecision::unchecked,Allocator>,boost::multiprecision::et_off>' (or there is no acceptable conversion)

Is there perhaps a way to use boost::multiprecision::sqrt() rather than cnl::sqrt() to deal with this issue?  I appreciate any suggestions.

Thanks!

**Comment by johnmcfarlane** [comment]
I think that even a short-term fix is going to take time. I can get past the shift operator problem but the result I get back is `141.418`! Clearly I need to dig a bit further.

Even once this is fixed, `cnl::sqrt` might be quite slow. And it will not straight-forward to use `boost::multiprecision::sqrt()` because the scale will be wrong for any fixed-point type with an exponent other than zero. 

I'll certainly keep this issue open and dig further but please don't hold your breath. For now, the standard `long double` overload of `std::sqrt` is the only other suggestion I have.

**Comment by johnmcfarlane** [comment]
I've implemented the quick fix so you should be able to use `cnl::sqrt` in conjunction with `fixed_point` or Boost.Multiprecision types. However a few things to note:
* there may be a few situations where you get compiler failure or UB depending on the input value and the exponent of the `fixed_point` type.
* this function may be ***quite slow*** at run-time. For now, don't depend upon it for performance-critical applications.

There's plenty to be done to improve the above and to tap into `boost::multiprecision::sqrt()` but it's a lot of work. I'd prefer to react to missing functionality as it is encountered by users. That way, I can make better use of my time so please don't stop providing feedback as you find things missing, broken or too slow for purpose. Thanks, John

**Comment by RallyTronics** [comment]
Thanks John, I look forward to playing with it.
