### ISSUE TITLE
Using more than 30 bits for scale?

### ISSUE THREAD

**Issue by punto-** [johnmcfarlane/cnl#311]
Hi. I'm trying to use fixed point on an int64_t type, with 32 bits for the fractional part, so I tried to declare like this:

`typedef cnl::fixed_point<std::int64_t, -32> real_t;`

but I'm getting the error "attempted operation will result in overflow", with a bunch of templates like "cnl::scale<31,2,S,void>" (with S=int). If I use -30 instead of -32 it works, but now I suspect that some temporary values will be stored on an int using 30 bits for the fractional part? Is this this the right approach? Thanks

**Comment by johnmcfarlane** [comment]
Can you give examples of the code you've written which results in the error? If you are you using `int`s (including literals such as `0`) then you cannot shift left by >30 bits without overflowing the entire value. You will want to use `std::int64_t` instead and wrap your literals in  `INT64_C`, e.g. `INT64_C(0)`.

**Comment by punto-** [comment]
It looks like it's a problem with the comparison, this code triggers the error:

```c++
#include "cnl/fixed_point.h"

typedef cnl::fixed_point<std::int64_t, -32> real_t;

int main(int argc, char** argv) {

	real_t n = 5.0;
	if (n > 0) ;
	return (int)n;
};
```

due to the "n > 0" part. Isn't there an operator>(int) ?

**Comment by johnmcfarlane** [comment]
There is a comparison operator but it first converts `0` to `cnl::fixed_point<int, 0>` because that's the equivalent fixed-point type for `int` and `0` is an `int`. 

It then scales the value to match `real_t` which means converting it to `cnl::fixed_point<int, -32>`. As you might imagine, that means shifting an `int` by 32 bits which entirely flushes the values.

The simple fix, as I mentioned is to replace `0` with `INT64_C(0)` or `0LL`: https://www.godbolt.org/z/y8d4HV

**Comment by johnmcfarlane** [comment]
Explained in FAQ in #924
