### ISSUE TITLE
Best way to serialize a fixed_point?

### ISSUE THREAD

**Issue by punto-** [johnmcfarlane/cnl#319]
Hi, I'm using fixed_point<std::int64_t, -32>, is there a way to get the integer part and fractional part as separate ints for serialization? I assume I can cast to int32_t for the int part, how do I get the fractional part on a uint32_t? I'd like to avoid any behind the scenes rounding, etc. Thanks!

**Comment by johnmcfarlane** [comment]
Hi. Firstly, do you want to serialize in human-readable decimal format? If so, `cnl::to_string` works except for one edge case. (Issue filed: #321.)

Otherwise, you can just write out the value as raw memory, e.g. with [std::ostream::write](https://en.cppreference.com/w/cpp/io/basic_ostream/write) or [std::fwrite](https://en.cppreference.com/w/cpp/io/c/fwrite). I haven't formalized the guarantee that this will work but `fixed_point<T>` will always be bitwise equivalent to `T`. Note that this is not robust if you care about endianness. 

To get at the value in a endian-agnostic way, perhaps `cnl::to_rep` is what you're after. This will give you the `int64_t` value which you can then serialize the same way you'd serialize a raw `int64_t`. To recreate the value from the deserialized `int64`, the complementary function is `cnl::from_rep<cnl::fixed_point<std::int64_t, -32>>{}(i)`.

That way, you don't need to care about splitting up the value. But if you really want to do that, here's [a function that should do the job](https://godbolt.org/z/saRCSG). Note that converting to `int32_t` is different to shifting by `32`. That's actually where rounding becomes an issue.

Hope that helps.

**Comment by punto-** [comment]
It's binary format, to transmit over the network. My int serialization code
handles spacial cases when the number uses 1, 8 or 16 bits (instead of the
full 32), so I think splitting will benefit from that. I'll try the to/from
rep method with shifting. Thanks!
