### ISSUE TITLE
Rounding when converting from float

### ISSUE THREAD

**Issue by vanossj** [johnmcfarlane/cnl#403]
Is there a way to allow rounding when constructing a fixed_point number from a float?

```c++
71 == to_rep(fixed_point< uint32_t, -9 >{0.1406})
```
72 would be closer to the ideal floating point value.

**Comment by johnmcfarlane** [comment]
If you want `fixed_point` to have round-to-nearest behavior, you can [instantiate it with `rounding_integer`](https://godbolt.org/z/mt44sX):

    auto f = fixed_point<rounding_integer<int>, -9>{0.1406};
    auto r = _impl::to_rep(_impl::to_rep(f));
    return r;

Note that this involves extra computation. Basically one needs to add/subtract .5 to some operations.

**Comment by vanossj** [comment]
In this particular case I'm setting up filter coefficients want to convert the ideal value to closest value in fixed point precision. After that the math is normal non rounding integer operations.

Changing the `Rep` type from `rounding_integer` to `int` via the `fixed_point` constructor doesn't work.
```c++
auto a = fixed_point<rounding_integer<int>, -9>{0.1406};
auto b = fixed_point<int, -9>(b);
```

but I can fall back to to_rep/from_rep
```c++
auto a = fixed_point<rounding_integer<int>, -9>{0.1406};
auto b = _impl::from_rep<fixed_point<int,-9>>(_impl::to_rep(_impl::to_rep(a)));
```

**Comment by hbe72** [comment]
I worked with John exactly on this with CDSP earlier. In DSP you need a proper fixed-point rounding type. Or alternatively explicit rounding operations between types. See the link to CDSP from readme of CNL.

Implicit rounding can be done by constructing type which does this you. However this causes some runtime penalty due to additional code.

```cpp
namespace cdsp
{
template<
    int IntegerDigits,
    class RoundingTag = cnl::nearest_rounding_tag,
    class Narrowest = int>
using rounding_elastic_integer = cnl::rounding_integer<
    cnl::elastic_integer<
        IntegerDigits,
        Narrowest>,
    RoundingTag>;

template<int Digits, int Exponent = 0, class RoundingTag = cnl::nearest_rounding_tag, class Narrowest = signed>
using rounding_elastic_number = cnl::fixed_point<rounding_elastic_integer<Digits, RoundingTag, Narrowest>, Exponent>;
}

// Elastic fixed point types equivalent to Cirrus ADSP2
typedef cdsp::rounding_elastic_number<24, -20> q4_20;
typedef cdsp::rounding_elastic_number<48, -40> q8_40;
```

Whole array of coefficients rounded correctly:
```cpp
std::array<q4_20, 5> coeff { { 0.274726851035635,  0.549453702071270, 
0.274726851035635, -0.073623846384979, 0.172531250527518 } };
```
or implicit rounding between types
```cpp
    static constexpr auto a = cdsp::rounding_elastic_number<8, -4>{0.4375};
    static constexpr auto b = static_cast<cdsp::rounding_elastic_number<4, -1>>(a);
    static_assert(identical(cdsp::rounding_elastic_number<4, -1>{0.5}, b),
              "rounding_elastic_number");
    static_assert(identical(cdsp::rounding_elastic_integer<8>{7}, to_rep(a)),
              "rounding_elastic_number");
    static_assert(identical(cdsp::rounding_elastic_integer<4>{1}, to_rep(b)),
              "rounding_elastic_number");
```

Benefit is that you get the implicit rounding between the types in assignment from wider accumulator type to narrower storage type. Drawback is that in all arithmetics you have the penalty of that rounding. That is the main reason why in most DSP instruction sets there is explicit round instruction. To simplify the hardware.

If you use CNL for the fixed-point design and reference for the final DSP implementation, the run time penalty does not matter. Using the code as final implementation code we should think what could be done to optimise the type above.

cnl::_impl::convert has some of explicit rounding in place. But that can not be used to cast arrays to correct fixed point representation.

Ps. I just started a branch to update the CNL version to current CNL development head. Windows build seems to be broke but Linux and Mac builds work on that branch.

**Comment by vanossj** [comment]
Thanks, `cnl::_impl::convert` looks like it does just what I need it to.

**Comment by johnmcfarlane** [comment]
Sorry @hbe72 I just noticed I broke CDSP by removing free functions such as `cnl::convert`! I should put those back ASAP.

Another break was the `__int128` streaming operators which I've since fixed.

**Comment by johnmcfarlane** [comment]
API break tracked in #414.
