### ISSUE TITLE
Using to_rep

### ISSUE THREAD

**Issue by imgod2u** [johnmcfarlane/cnl#655]
I have a rather odd compile error:

https://godbolt.org/z/a5e1oK

I've seen this when writing operator extensions for CNL as well. to_rep apparently has multiple implementations? And the one accessed by cnl::to_rep doesn't just take a value, it requires some other template syntax?

My C++ isn't strong enough to understand the difference from the documentation.

I tried the following:

https://godbolt.org/z/roj7Mh

Which seemed to recognize the object now. But then there's no '<<' operator for that object...

**Comment by johnmcfarlane** [comment]
OK, so there's a bit of a gap in the interface there -- mostly because three different entities are vying for the same name: the class, `cnl::to_rep` which provides the customisation point for different types, the alias to that class, `cnl::to_rep_t`, and the function which provides type deduction so you don't need to repeat the type in angle brackets, `cnl::_impl::to_rep`.

The last of these is what you're really after ([example](https://godbolt.org/z/87nGvM)) but it's not a supported API. Confusing this with the class is why you're workaround doesn't work. `cnl::to_rep` is a function object which you first need to instantiated before calling so there's a second set of brackets there ([example](https://godbolt.org/z/hGxG17]).

Of the two example solutions, the former is cleaner but expect it to break at some point in the future without warning because it's in the `_impl` namespace!

**Comment by imgod2u** [comment]
Thanks John. So curiously I've been doing this successfully:
https://godbolt.org/z/YKnGez

If I don't specify the cnl namespace, it somehow is able to lookup a to_rep function that works. Any idea what it's actually calling?

**Comment by johnmcfarlane** [comment]
I believe that's [ADL](https://en.cppreference.com/w/cpp/language/adl). I'll need fix this in CNL 2; it's pretty surprising behaviour.
