### ISSUE TITLE
Negative 15.16 number saturating at 0x8000_0001

### ISSUE THREAD

**Issue by imgod2u** [johnmcfarlane/cnl#657]
I have the following code:

https://godbolt.org/z/afa8E9

It's two 15.16 signed numbers that result in a negative saturated result. The maximum negative number (lowest number) seems to be 0x8000_0001 (-32767.9999847412109375). But I'd expect it to be 0x8000_0000? As that's the lowest 2's complement number possible.

Is this intended behavior? And if so, why? Also, is there a setting to change this?

**Comment by johnmcfarlane** [comment]
`elastic_integer` doesn't allow the most negative number because otherwise `-n` or `n/-1` could overflow. That type is designed to ensure safety and the most negative number isn't compatible with that end.

There should always be an escape hatch if you want to take control and accept risk. In this case, CNL still allows manual promotion to a wider type: https://godbolt.org/z/PPPEde. This does exactly what you're after, but `elastic_integer` cannot accompany you because you're deliberately persuing the one value which is hardest for beginners to use safely.

I hope that makes sense.

**Comment by imgod2u** [comment]
Thanks John. So I'm doing this in a templated class which I'd hope to be able to pass in cnl::fixed or float (native) or any other one type. To manually promote, I'd have to add a second template, which I'd hoped to abstract from this.

Maybe I can overload the * operator for q15_16 in your example? How would I go about doing that?

**Comment by johnmcfarlane** [comment]
The combination of things you're looking for is pretty hard to reconcile:
* genericity between float and fixed-point;
* most negative number;
* simple saturation when it's fixed-point: numbers won't overflow but the type cannot remember that it's saturated, leading to some 'interesting' behaviour (see #381);
* sticky saturation when it's floating-point (which you probably won't need because of the greater range of floats).

Are you sure you need/want *all* of these properties?

Outside some quite specific DSP algorithms, saturation really isn't that desirable. You might want to consider whether you want explicit overflow checking at crucial points in your code, and make sure to avoid overflow elsewhere by having sufficient range.  E.g., you could work mostly in non-elastic q47_16, with multiplication automatically returning q31_32.

Otherwise, I think you're looking for a variant of elastic_integer which is slightly more error-prone, i.e. allows MNN. You might be able to do this with a tag that is almost the same as `elastic_tag` but really, the way customisation points work currently, it may involve specialising all generic operators -- tedious, but doable (and not as tedious as overloading every operator). This is all stuff I wouldn't want to pursue further without being able to use concepts.

**Comment by imgod2u** [comment]
So I can give up on the most negative number. I've verified that it doesn't matter much for the algorithm I'm working on.

You're right that I likely won't need to worry about floats being saturated.

A generic interface between fixed/float (or my own custom data-type) is highly desirable for algorithm study (minimal code change when swapping data types).

But I think the thing that matters right now to me is the rounding mode in https://github.com/johnmcfarlane/cnl/issues/659. Having it always follow the C style integer division (essentially signed floor) would introduce errors over time. Could we discuss whether that's achievable in that issue?
