### ISSUE TITLE
Truncation behavior rather than floor() after multiplying

### ISSUE THREAD

**Issue by imgod2u** [johnmcfarlane/cnl#659]
The following code:

https://godbolt.org/z/v9P9rn

Has a negative result of multiplying two signed 15.16 numbers (one positive, one negative). When the multiply result is reduced from the 62-bit intermediate representation to a signed 15.16 number, a signed floor() function is used. Is there a flag to pass to the type to make reductions do simple truncation (i.e. throw away the bottom bits).

**Comment by johnmcfarlane** [comment]
Firstly, multiplying is unrelated to the rounding here. Multiplication is lossless (assuming the result is not too big) and therefore rounding doesn't affect it. The rounding in your example happens when converting to a type with fewer fractional digits. You see the same result with [this simplified example](https://godbolt.org/z/GvPKh8) without multiplication.

Secondly, no `floor()` function is used. The 64-bit value is simply scaled using integer division and the result is indeed truncated. Note that the result is actually greater than the original value. That is what happens when a negative number is truncated. There's a helpful graph on the [`std::floor()`](https://en.cppreference.com/w/cpp/numeric/math/floor) page of cppreference.com which should make it clear that when you floor a negative value, you get a *lower* value with a *greater* magnitude.

Hope that makes sense.

**Comment by imgod2u** [comment]
Thanks John. Yes I didn't mean the multiply itself is truncating. Simply that I'm arriving at the truncation behavior by multiplying first and then scaling down to a signed 15.16 number.

With regard to your second point, I know that no floor function is used but since you are scaling the signed integer by division, that does mean CNL does effectively floor, as per the spec of std::floor(). Am I correct in that assessment?

What I would ideally want is an unsigned truncation. Or rather, simply taking bits 47:16 of the underlying representation. I'm modeling hardware that wants to do this.

Moreover, I am doing this in a templated class where I will be swapping out float for cnl::fixed_point and vice versa. So I'd like the code to simply be:

```c++
template <typename T>
void my_func(T a, T b, T c, T& z) {
  T a, b, c, z;
   z = a * b + c;
}
```

So if I have to go through manual steps, it looks like I'd have to overload the conversion operator. Could you show me where that is?

**Comment by imgod2u** [comment]
Circling back on this. I think I can get away with nearest-rounding mode. That is, an elastic integer base (expands during multiply) that will convert to a 32-bit signed internal representation using nearest-rounding. And also saturates on overflow (can be 0x8000_0001).

I tried something like this:
https://godbolt.org/z/GfrvWc

But it seems to still round the same way (floor int type). Am I doing that right?

**Comment by hbe72** [comment]
See v1_fixed_point_division branch. Yes I know it is badly named, but originally I had question about the fixed point division. I fixed some tests for the the "tie_to_pos_inf_rounding_tag" (which is essentially add "half" and truncate for the HW designers) and then implemented floor_rounding_tag (that is 2's complement truncate rounding mode). These are the two ones the signal processing HW designers tend to use. These seem to work correctly, but I have not heavily tested these.  

I probably still need to rename that according to [p0105r1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0105r1.html#RoundMode) to from floor_rounding_tag to neg_inf_rounding tag to be on par with tie_to_pos_inf rounding tag. 

If we see these to fit our needs I make the final changes and John can marge/rebase these to v1 branch.

**Comment by hbe72** [comment]
Now renamed. Thus if you now would use neg_inf_rounding_tag, you get desired 2's complement truncation rounding mode, which rounds towards negative infinity.

**Comment by imgod2u** [comment]
I've talked to the hardware guy and he's implemented a full rounding mode. So I'll be modeling that. cnl::rounding integer (per my code above) works. But unfortunately, it also sees an error when I try to combine it with elastic and overflow integers....

**Comment by imgod2u** [comment]
Thanks hbe72; I'll keep that branch in my back pocket for when the hardware does 2's complement truncation rounding.

**Comment by hbe72** [comment]
I'll hope John has time to look at the branch. I think is good enough to be integrated to v1 branch, and bump the version to v.1.0.1, if he finds why the compilation does not work without INT128 support. The same error is in current v.1.0.0 with tie_to_pos_inf rounding mode, but there are no tests to expose the error. All rounding modes would always benefit of more rigorous testing.

**Comment by johnmcfarlane** [comment]
@imgod2u 

> It would seem that a combination of overflow, rounding and elastic integer would push the internal representation higher than 128 bits (max supported by CNL). Any advice on this?

Is this still an issue?

**Comment by imgod2u** [comment]
Hi John, it is still an issue. However I've worked around it and basically abandoned elastic_integer. I went ahead and overloaded the * operator for my specific type:

```c++
using s15_16_rep = int32_t;
using s15_16_scale = cnl::power<-16>;
using s15_16_ovfl = cnl::overflow_integer<s15_16_rep, cnl::saturated_overflow_tag>;
using s15_16_round = cnl::rounding_integer<s15_16_ovfl, cnl::nearest_rounding_tag>;
using fp = cnl::scaled_integer<s15_16_roundingl,s15_16_scale>;

namespace cnl {
fp operator * (const fp& x, const fp& y) {
// code that handles expanding to 64-bit intermediate and truncation
return my_fp;
}
```

To get both the expanding and truncation, overflow and rounding behavior that I was after.

Can you verify that 128-bit is the absolute limit? And that trying to combine elastic_integer, rounding_integer and overflow_integer like I tried violated this? We can then close this issue.

**Comment by johnmcfarlane** [comment]
There is a wide_integer type but that is nowhere near reliable. I'll leave this issue open for now but am I right in assuming that the problem you currently have is no longer about rounding modes but about numbers getting too wide during multiplication?

**Comment by imgod2u** [comment]
Well, it would be nice to have configurable rounding the way that hbe72 described. For my particular use-case, I was able to verify that the algorithm doesn't need the type of rounding I originally requested.

**Comment by johnmcfarlane** [comment]
@hbe72

> Now renamed. Thus if you now would use neg_inf_rounding_tag, you get desired 2's complement truncation rounding mode, which rounds towards negative infinity.

Confused: isn't rounding towards -ve infinity different to truncation for -ve values?

**Comment by hbe72** [comment]
> Confused: isn't rounding towards -ve infinity different to truncation for -ve values?

In two's complement binary representation dropping away the bits is equivalent to rounding towards negative infinity. 
0011.0100 is 3.25
1100.1100 is -3.25

Now let's truncate -3.25
1100.1 is -3.5

**Comment by johnmcfarlane** [comment]
@hbe72 Of these two opposing things described as 'truncation', the former is likely to confuse other users who are not aware of -- or concerned with -- the underlying implementation and its peculiarities, just like it is confusing me!

I think most people would say that if you truncate -3.25, you get -3. I would suggest that we find a different word for the thing that you and @imgod2u are describing. 

Suggestion: just as right shift comes in two flavours: bitwise and arithmetic, so truncation should be qualified as either arithmetic truncation and bitwise truncation. Just as with right shift, bitwise truncation is the same as arithmetic truncation for non-negative values and unsigned types. And unless specified, truncation should refer to arithmetic truncation so that the model is simpler for users to follow, more implementation-agnostic and more consistent with expectation WRT floating-point behaviour.

**Comment by hbe72** [comment]
@johnmcfarlane Yes it is difficult to discuss of the terminology is not exact. I understand now that truncation is a term generally used for signed magnitude values. The terminology should be common to more SW oriented and HW oriented users of the library. Sometimes it is difficult if you are accustomed to using and understanding the terms differently in your respective domain. But yes binary truncation is very different than arithmetic truncation. 

Unfortunately I did state in the comments of [here](https://github.com/johnmcfarlane/cnl/blob/ae38c7d0c6eb1257e3b5f64370a2bfe8443d3ac0/include/cnl/_impl/rounding/neg_inf_rounding_tag.h#L21), that "Arithmetic operations using this tag round by truncating 2's complement binary representation, thus round all values towards minus infinity". It would have been sufficient to say this implements "round towards neg infinity rouding" and say nothing about 2's complement. I would imagine the ones who are after 2's complement binary truncation should understand it to be equivalent to rounding towards negative infinity.

**Comment by johnmcfarlane** [comment]
@hbe72 Yes, incorrect would be worse than terse so that's fine. Given all of that, is @imgod2u 's original mode now supported?

**Comment by hbe72** [comment]
Yes

**Comment by johnmcfarlane** [comment]
Thanks @hbe72. OK, I'm inclined to close this issue then. @imgod2u, try `neg_inf_rounding_tag` rounding mode if it turns out you need the originally-requested behaviour.

In the longer term, the type, `static_number` is a type that combines properties from many other types in the library including `wide_integer` which supports arbitrary width. It is a longer-term aim of the project to make these types reliable and the transition to C++20 should make that a lot easier because many of the algorithms related to wide integers are better expressed using loops, than with recursion. Recursion is required, however, due to limitations in C++11 constant expressions. Concepts will also help move this work along. Note, though, that these are long-term goals with no timeline currently for achieving them.

Please don't hesitate to open a new issue if there are any outstanding issues arising from this thread.
