### ISSUE TITLE
Division between scaled_integer returns integer 

### ISSUE THREAD

**Issue by emiliopaolini** [johnmcfarlane/cnl#806]
I don't know if it is bug or it must be this way, but this code doesn't work as one would expect:
using float_x = cnl::scaled_integer<cnl::overflow_integer<cnl::signed_multiprecision<20>,cnl::saturated_overflow_tag>,cnl::power<-8>> ;
float_x c{10.0};
float_x a = 1.0;
cout<<a/c<<endl;//prints 0
cout<<float_x(1.0/c)<<endl;//prints correct results
What i am asking if this is a design choice or a possible bug. A question that i have is that: is it possible to define a custom operator / ?

**Comment by johnmcfarlane** [comment]
Hi. 

It's a design choice -- and a vexing one for many users. `scaled_integer` uses integer division, not floating-point division. It is the most precise and run-time efficient but is also quite surprising and disappointing to anyone expecting a drop-in replacement to floating-point types.

Here's [a demonstration similar to yours using CNL 1.x](https://godbolt.org/z/473rMa).

The fact of the matter is that your example doesn't print entirely correct results but an approximation, `0.09765625`. Floating-point numbers have a known precision that's easy to mintain because they have a dynamic exponent. Fixed-point numbers have a fixed exponent so they cannot do the same. Either the user must chose what precision they want or a system needs to be in place which makes that decision.

In this [slightly different demonstration](https://godbolt.org/z/oPo94q), the type of `a` has been adjusted to add more fractional precision and you get the result you're looking for. That the result has less precision than the dividend is hard to comprehend, but it's a natural consequence of applying integer division to fixed-point values.

I have plans (#788) to make this problem go away for users who are happy with slower calculations and even-more-vexing edge cases. It will essentially work by overriding `operator/` -- as you suggest -- for a variant of scaled_integer.

Before that, I plan (#753 ) to add a section to the FAQ to explain this behaviour. You are by no means the first person to ask this same question.
