### ISSUE TITLE
Q: Double overflow undetected

### ISSUE THREAD

**Issue by hbe72** [johnmcfarlane/cnl#830]
I'm experimenting with v1.1.7 of CNL and stumbled on a "feature" on double to fixed_point conversion:

```cpp
#include <cnl/all.h>
#include <cnl/_impl/type_traits/identical.h>
#include <gtest/gtest.h>

using cnl::_impl::identical;

namespace {
    namespace double_overflow {
        static_assert(identical(cnl::static_number<16, -15>{2.0}, cnl::static_number<16, -15>{2.0}));
    }
}

TEST(math, double_overflow)
{
    cnl::static_number<16, -15> a{2.0};
    cnl::static_number<16, -15> b{2.0};
    EXPECT_EQ(a, b);
}
```

First of all we should not be able to store 2.0 in <16, -15> fixed-point number. Perhaps that should saturate or in case of static evaluation miscompile.

Static test miscompiles and terminates with "__builtin_unreachable()' is not a constant expression". I'm suspecting that this is expected behavior. 

The googletest, however, compiles without problems and runs, but terminates with: 
```bash
berg@hebembp unit % ./test-unit-math
Running main() from /Users/berg/.conan/data/gtest/1.10.0/_/_/build/bad44111921e526997f97d9d87c5ebadc23cc354/source_subfolder/googletest/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from math
[ RUN      ] math.double_overflow
zsh: illegal hardware instruction  ./test-unit-math
```

I'm curious why googletest compilation of the similar thing i.e. 2.0 converted to cnl::static_number<16, -15> did not miscompile? 

Even this compiles:
```cpp
TEST(math, double_overflow)
{
    if (identical(cnl::static_number<16, -15>{2.0},cnl::static_number<16, -15> {2.0})){
        cnl::static_number<16, -15> a{2.0};
        cnl::static_number<16, -15> b{2.0};
        EXPECT_EQ(a, b);
    }
}
```
but terminates with "zsh: illegal hardware instruction  ./test-unit-math"

**Comment by johnmcfarlane** [comment]
> I'm curious why googletest compilation of the similar thing i.e. 2.0 converted to cnl::static_number<16, -15> did not miscompile?

The former (the `static_assert`) is a constant expression. [Constant expression may not contain undefined behaviour](https://eel.is/c++draft/expr.const#5.7).

The latter is a run-time expression. It is syntactically correct, but exhibits undefined behaviour when run.

> Perhaps that should saturate

Saturation produces incorrect results. I'd rather that incorrect behaviour was an opt-in. 

> or in case of static evaluation miscompile.

Miscompilation is not possible because this isn't a compile-time error. Yes, by running some of the program during compile-time, the compiler *could* determine that the code will be illegal at run-time but it's dangerous to start diagnosing such errors in the compiler because it's impossible to catch every such error in a bounded amount of time. Compile times would end up many times longer than they already are and the user would be lulled into a false sense of security, as some run-time errors would be detected and others would not. 

A static analysis program is welcome to diagnose such a problem. However, I've found that Clang-Tidy is especially poor at diagnosing UB in C++.

> Static test miscompiles and terminates with "__builtin_unreachable()' is not a constant expression". I'm suspecting that this is expected behavior.

Yes, I'm glad to hear that this happens. It's because `undefined_overflow_tag` is the default.

> Even this compiles: ... but terminates with "zsh: illegal hardware instruction ./test-unit-math"

That's interesting. `identical` is being invoked at run-time. It's being put inside the `static_assert` that forces a `constexpr` function to be constant-evaluated.

**Comment by johnmcfarlane** [comment]
When to expect overflow errors is [mentioned now](https://johnmcfarlane.github.io/cnl/index.html#overflow) in the FAQ.
