### ISSUE TITLE
How to access internal representation of a custom scaled_integer

### ISSUE THREAD

**Issue by emiliopaolini** [johnmcfarlane/cnl#902]
Hi everyone, i have the following problem: i need to access the internal integer representation of this type:
`using fp = cnl::scaled_integer<cnl::overflow_integer<cnl::signed_multiprecision<64>,cnl::saturated_overflow_tag>,cnl::power<-20>>;`
I know that there exists the to_rep function but it gives me an issue when i do the following:
` fp v1{3.75};
long int v1_rep = cnl::to_rep<fp>{}(v1);
`
Thanks in advance!!

**Comment by johnmcfarlane** [comment]
Hi @emiliopaolini,

The problem appears to be in the conversion from the Boost.Multiprecision type to `long int` which isn't implicit. There are several ways around this depending on what type of integer you actually need. If you just leave the type as the `scaled_integer`'s `rep` type, it compiles:

```c++
auto v1_rep = to_rep(v1);
```

([Example](https://godbolt.org/z/48Te53M3e).) This is usually a good approach because fewer conversions will take place and you've no oppotunity to get the type wrong.

But if you really need it to be `long`, you can cast explicitly or initialise a `long` from it:

```c++
auto v1_rep_as_long = long{to_rep(v1)};
```

([Example](https://godbolt.org/z/fj8Txvc4c).)

HTH,
John
