### ISSUE TITLE
Suggestion for FAQ: note on performance

### ISSUE THREAD

**Issue by dnmiller** [johnmcfarlane/cnl#905]
I was testing out CNL in a bit of code I already had written using raw ints, and I was shocked to see my execution time go up by about 100x after writing the same code with CNL. This was with LLVM 12 on MacOS. 

Eventually I realized I was in the debug build, and turning on optimizations gave equal performance. Would it make sense to include a note in the FAQ that compiling without optimizations enabled may cause significant performance penalties?

**Comment by johnmcfarlane** [comment]
Hi. It's increasingly common for C++ libraries to require inlining in order to perform well. You could argue that this is the domain of modern C++ user -- rather than CNL user in particular. That said, it's an especially acute problem for a library like this.

Can I ask what docs your read first. Did you read the [README.md](https://github.com/johnmcfarlane/cnl/blob/main/README.md)? Did you read [the front page of the documentation](http://johnmcfarlane.github.io/cnl/)? In particular, did you look through the FAQ first for advice? If I was going to mention performance, it would help to know where users would find it.

Thanks,
John
